name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # รันอัตโนมัติทุกวัน
  workflow_dispatch: # ปุ่มกดสั่งรันเอง

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write # 👈 ให้สิทธิ์บอท Push ไฟล์เข้า Repo

    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          # เช็คว่ามีไฟล์ใหม่ไหม ถ้ามีค่อย Commit & Push (กัน Exit Code 128)
          if ! git diff --staged --quiet; then
            git commit -m "generated 3d contrib"
            git push
          else
            echo "No changes to commit"
          fi
